use_frameworks!

platform :ios, '11.0'

target 'SwifterKit_Example' do
  pod 'SwifterKit', :path => '../'

  target 'SwifterKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
